<?php


use Drupal\Core\Render\Markup;
use Drupal\Core\StringTranslation\TranslatableMarkup;

/**
 * Implements hook_menu_links_discovered_alter().
 */
function poll_menu_links_discovered_alter(&$links) {
 unset($links['system.admin_content']);
}

/**
 * Implements hook_theme().
 */
function poll_theme($existing, $type, $theme, $path) {
  return [
    'poll_invitation' => [
      'variables' => [
        'subject' => NULL,
        'poll_name' => NULL,
        'participant_name' => NULL,
        'poll_link' => NULL,
      ],
      'template' => 'poll-invitation',
    ],
  ];
}

/**
 * Implements hook_mail().
 */
function poll_mail($key, &$message, $params) {
  switch ($key) {
    case 'invite':
      $template = [
        '#theme' => 'poll_invitation',
        '#subject' => $params['subject'],
        '#poll_name' => $params['poll_name'],
        '#participant_name' => $params['participant_name'],
        '#poll_link' => $params['poll_link'],
      ];

      $html = \Drupal::service('renderer')->renderRoot($template);

      $message['subject'] = $params['subject'];
      $message['body'] = [Markup::create($html)];
      $message['headers']['Content-Type'] = 'text/html; charset=UTF-8';
      break;
  }

}
