<?php

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_type_alter().
 */
function pipeline_run_entity_type_alter(array &$entity_types) {
  /** @var $entity_types \Drupal\Core\Entity\EntityTypeInterface[] */
  if (isset($entity_types['pipeline_run'])) {
    $entity_types['pipeline_run']->setFormClass('add', NULL);
    $entity_types['pipeline_run']->setFormClass('edit', NULL);

    // Remove the 'add-form' and 'edit-form' link templates
    $link_templates = $entity_types['pipeline_run']->getLinkTemplates();
    unset($link_templates['add-form']);
    unset($link_templates['edit-form']);

    // Set the updated link templates
    foreach ($link_templates as $key => $path) {
      $entity_types['pipeline_run']->setLinkTemplate($key, $path);
    }
  }
}

/**
 * Implements hook_entity_operation_alter().
 */
function pipeline_run_entity_operation_alter(array &$operations, EntityInterface $entity) {
  if ($entity->getEntityTypeId() == 'pipeline_run') {
    // Remove the clone operation
    unset($operations['clone']);
  }
}

function pipeline_run_theme($existing, $type, $theme, $path) {
  return [
    'pipeline_run_steps' => [
      'variables' => [
        'pipeline_run' => NULL,
        'steps' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_views_pre_render().
 */
function pipeline_run_views_pre_render(\Drupal\views\ViewExecutable $view) {
  if ($view->id() == 'pipeline_runs' && $view->current_display == 'embed_1') {
    // Translate field labels
    foreach ($view->field as $field_id => $field) {
      switch ($field_id) {
        case 'status':
          $field->options['label'] = t('Status');
          break;
        case 'duration':
          $field->options['label'] = t('Duration');
          break;
        case 'triggered_by':
          $field->options['label'] = t('Triggered By');
          break;
        case 'start_time':
          $field->options['label'] = t('Start Time');
          break;
        case 'end_time':
          $field->options['label'] = t('End Time');
          break;
        case 'created_by':
          $field->options['label'] = t('Created By');
          break;
        case 'id':
          $field->options['label'] = t('Step details');
          break;
      }
    }
  }
}
