poll.poll.*:
  type: config_entity
  label: 'Poll'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    instructions:
      type: text
      label: 'Instructions'
    status:
      type: string
      label: 'Status'
    langcode:
      type: string
      label: 'Language code'
    created:
      type: integer
      label: 'Created timestamp'
    changed:
      type: integer
      label: 'Changed timestamp'
    llm_analysis:
      type: mapping
      label: 'LLM Analysis Results'
      mapping:
        raw_response:
          type: string
          label: 'Raw LLM Response'
        processed_data:
          type: string
          label: 'Processed Analysis Data'
    closed_date:
      type: integer
      label: 'Date Closed'
      nullable: true
    question_types:
      type: sequence
      sequence:
        type: mapping
        mapping:
          id:
            type: string
          data:
            type: poll.question_type.[%parent.id]
          weight:
            type: integer
          uuid:
            type: string

poll.question_type.*:
  type: mapping
  label: 'Question type settings'
