pipeline.pipeline.*:
  type: config_entity
  label: 'Pipeline'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    instructions:
      type: text
      label: 'Instructions'
    status:
      type: boolean
      label: 'Status'
    langcode:
      type: string
      label: 'Language code'
    created:
      type: integer
      label: 'Created timestamp'
    changed:
      type: integer
      label: 'Changed timestamp'
    execution_type:
      type: string
      label: 'Execution Type'
    scheduled_time:
      type: integer
      label: 'Scheduled execution timestamp'
    schedule_type:
      type: string
      label: 'Schedule Type'
    recurring_frequency:
      type: string
      label: 'Recurring Frequency'
    recurring_time:
      type: string
      label: 'Recurring Time'
    execution_interval:
      type: integer
      label: 'Execution Interval'
      nullable: true
    execution_failures:
      type: integer
      label: 'Execution Failures Count'
    entity_type:
      type: string
      label: 'Entity Type'
      nullable: true
    bundle:
      type: string
      label: 'Bundle'
      nullable: true
    step_types:
      type: sequence
      sequence:
        type: mapping
        mapping:
          id:
            type: string
          data:
            type: pipeline.step_type.[%parent.id]
          weight:
            type: integer
          uuid:
            type: string

pipeline.step_type.*:
  type: mapping
  label: 'Step type settings'

views.filter.rag_indexing_status_filter:
  type: views.filter.in_operator
  label: 'RAG Status filter'
  mapping:
    value:
      type: sequence
      label: 'Values'
      sequence:
        type: string
        label: 'Value'

views.filter.field_rag_indexing_status_value:
  type: views.filter.in_operator
  label: 'RAG indexing status'
  mapping:
    value:
      type: sequence
      label: 'Status'
      sequence:
        type: string
