<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\poll\Entity\Poll;

/**
 * Implements hook_entity_type_alter().
 */
function participant_entity_type_alter(array &$entity_types) {
  if(isset($entity_types['participant']) && $entity_types['participant'] instanceof Poll) {
    $entity_types['poll']?->setLinkTemplate('participants', '/admin/structure/poll/{poll}/participants');
  }
}

/**
 * Implements hook_entity_operation().
 */
function participant_entity_operation(EntityInterface $entity) {
  $operations = [];
  if ($entity->getEntityTypeId() === 'poll') {
    $operations['participants'] = [
      'title' => t('Manage Participants'),
      'weight' => 50,
      'url' => $entity->toUrl('participants'),
    ];
  }
  return $operations;
}

function generateUuid() {
  return \Drupal::service('uuid')->generate();
}
